variables:
  REGISTRY: sed-team-project:4567
  REG_SERVER: $REGISTRY/sed-dev-group/event-bus/bus
  REG_SERVICE: $REGISTRY/sed-dev-group/event-bus/service

stages:
  - build
  - test
  - publish

.dependencies: &dependencies |
  apt-get update
  apt-get install -y libev4 libssl1.0.0 cmake build-essential
  wget https://github.com/couchbase/libcouchbase/releases/download/2.8.1/libcouchbase-2.8.1_jessie_amd64.tar
  tar xf libcouchbase-2.8.1_jessie_amd64.tar
  dpkg -i libcouchbase-2.8.1_jessie_amd64/*.deb

build_service:
  image: rust:jessie
  stage: build
  script:
    - *dependencies
    - cd service
    - cargo build

build_event_bus:
  image: rust:jessie
  stage: build
  script:
    - *dependencies
    - cd server
    - cargo build

test_service:
  image: rust:jessie
  stage: test
  script:
    - *dependencies
    - cd service
    - cargo test

test_event_bus:
  image: rust:jessie
  stage: test
  script:
    - *dependencies
    - cd server
    - cargo test

prod_tag_service:
  image: docker:latest
  stage: publish
  script:
    - docker build -t $REG_SERVICE:master -t $REG_SERVICE:latest -f Dockerfile.service .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $REG_SERVICE:master
    - docker push $REG_SERVICE:latest
  only:
    - master

prod_tag_event_bus:
  image: docker:latest
  stage: publish
  script:
    - docker build -t $REG_SERVER:master -t $REG_SERVER:latest -f Dockerfile.server .
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY
    - docker push $REG_SERVER:master
    - docker push $REG_SERVER:latest
  only:
    - master
